scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'api-server'
    scrape_interval: 5s # for demo purpose
    static_configs:
    - targets: ['18.220.175.232:31000','18.220.175.232:31001']
